import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import reddit from "../common/utils/reddit";

const initialState = {
  title: "",
  primary_color: "",
  banner_background_color: "",
  banner_img: "",
  banner_height: 0,
  status: "unload",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchInfo = createAsyncThunk(
  "subredditInfo/fetchInfo",
  async ({ name = "" }) => {
    let subredditInfo = reddit.about(name);

    const response = await subredditInfo.fetch();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const subredditInfoSlice = createSlice({
  name: "subredditInfo",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchInfo.pending, (state) => {
        state.aboutStatus = "loading";
      })
      .addCase(fetchInfo.fulfilled, (state, action) => {
        state.aboutStatus = "loaded";
        if (action.payload) {
          state.title = action.payload.title;
          state.primary_color =
            action.payload.primary_color || action.payload.key_color;
          state.banner_background_color =
            action.payload.banner_background_color;
          state.banner_img = action.payload.banner_img;
          state.banner_height = action.payload.banner_size
            ? action.payload.banner_size[1]
            : 0;
        }
      });
  },
});

export const { updateArticleVote, updateSortBy, updateSortTime } =
  subredditInfoSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.subreddit.value)`
export const selectTitle = (state) => state.subredditInfo.title;
export const selectPrimaryColor = (state) => state.subredditInfo.primary_color;
export const selectBgColor = (state) =>
  state.subredditInfo.banner_background_color;
export const selectBannerImg = (state) => state.subredditInfo.banner_img;
export const selectBannerHeight = (state) => state.subredditInfo.banner_height;
export const selectInfoStatus = (state) => state.subredditInfo.status;

export default subredditInfoSlice.reducer;
